name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  kernel:
    runs-on: ubuntu-latest
    name: Build

    strategy:
      matrix:
        image-definition:
          - ubuntu-noble-arm64-tarball
          - ubuntu-noble-server-arm64-tarball

    steps:
      - name: Get more disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison \
          qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
          udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 \
          python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools \
          python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools \
          live-build livecd-rootfs golang-go

      - name: Build Docker 
        shell: bash
        run: docker build -t foobar docker
        
      - name: Build
        shell: bash
        run: docker run --privileged -v /dev:/dev --rm -v "$(pwd)":/opt foobar ubuntu-image classic -w work -O out ${{ matrix.image-definition }}.yaml

      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ matrix.image-definition }}
          path: ./out/*
          if-no-files-found: error
