name: build
on: [push]

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: download repo
        uses: actions/checkout@v4
      
      - name: run build
        run: |
          dd if=/dev/zero of=testfile.img bs=1M count=3072
          dd if=/dev/zero of=foobar.img bs=1M count=1024

      - name: create release
        uses: ading2210/gh-large-releases@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: ./*.img